### ISSUE TITLE
CoreTweet.V2 等の解決に失敗する

### ISSUE THREAD

**Issue by SlashNephy** [noriokun4649/TVTComment#43]
CI がコケていたので手元の環境でも試してみましたが、CoreTweet の解決に失敗してビルドに失敗してしまうようです。

[Nuget](https://www.nuget.org/packages/CoreTweet) でインストールできる CoreTweet のバージョンは 1.0.0.483 で、これには `CoreTweet.V2` 名前空間が含まれていません。
[Appveyor](https://ci.appveyor.com/project/azyobuzin/CoreTweet/build/artifacts) 上には 1.0.0.583 (V2 を含むバージョン) が公開されていますが、Nuget レジストリには同期されていないのが原因のようです。

CoreTweet の [リポジトリ](https://github.com/CoreTweet/CoreTweet) を Submodule 化して `ProjectReference` として取り込んでしまうか、Appveyor の nupkg をリポジトリに含んだりして解決できそうです。

ちなみに Submodule を CI 上で含めてビルドする際には https://github.com/SlashNephy/Dalamud.Divination.Template/blob/9ac6878f1558245d4eba01c573a6c9c862b4ba51/.github/workflows/build.yml#L36 のように `submodules: recursive` のような指定が必要です。

**Comment by noriokun4649** [comment]
この問題は既に理解していて、コケるだろうと思ってたので今回は直接Releaseに上げています。

なるほど、Appveyorだと公開されてるのですね。現在ローカルではCoreTweetのリポジトリをビルドした奴を使ってるので、Submodule化する方法は良さそうですね。

---

あと実はAnnictに関する処理もUserSecretでクライアントIDとシークレットを管理してる影響で、CIからの成果物だとエンドユーザ環境で動かないのでちょっと悩んでます。
GitHubのActions secretsで保存しておいて、CIで該当部分のソースコード直接置き換える強引な方法しか思いつけなかった。

**Comment by SlashNephy** [comment]
msbuild は環境変数も参照してくれるみたいですね
Secrets に格納しておいて、csproj内で環境変数を参照する方法が現実的っぽいです
https://docs.microsoft.com/ja-jp/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2019

**Comment by noriokun4649** [comment]
@SlashNephy 
Annict 含め機能するようになりました。
ご協力ありがとうございました。
