### ISSUE TITLE
数分経つと2chDAT取得エラーが発生する

### ISSUE THREAD

**Issue by medama** [noriokun4649/TVTComment#74]
2chDAT取得後しばらく経つと以下のエラーが発生します

"TVTCommentエラー
2chDATで以下のエラーが発生しました。このコメント元を無効化します。
サーバーからの返信にエラーがあります"

**Comment by noriokun4649** [comment]
イベントビューアのログはございますか？
視聴しているチャンネル・日時、該当スレ等の情報が無いと検証しようもありません。

**Comment by medama** [comment]
チャンネルや時間に関係はなく2chthreads.txtを"なんでも実況"系スレッドを取得するよう編集したものを使っています。
TVTestバージョンは0.10.0
イベントビューアのログは残っているかもう少し探してみます。

**Comment by noriokun4649** [comment]
> チャンネルや時間に関係はなく2chthreads.txtを"なんでも実況"系スレッドを取得するよう編集したものを使っています。

編集してるのであれば、そういった情報を言っていただかないと検証できませんし、編集内容も提示お願いします。

**Comment by medama** [comment]
お手数をおかけします。
[2chthreads.txt](https://github.com/noriokun4649/TVTComment/files/9640587/2chthreads.txt)

**Comment by noriokun4649** [comment]
ありがとうございます。
検証してみます。

**Comment by noriokun4649** [comment]
APIのレスポンスで404が返ってきているのが原因ぽいですね。
現状なぜ404が返ってきているか分からない上に、APIの完全な仕様がわからないので、
実装が原因で404が返ってきているのか、5ch側の問題なのかが分かりません。
後者であった場合は、私には根本的な解決は出来ません。

どちらにしろ、すぐに解決は出来そうにありません。

**Comment by medama** [comment]
了解しました。
余談ですが 、特に勢いのある時間にエラーが発生しやすいですね。

**Comment by noriokun4649** [comment]
APIを利用しなくなったので閉じます
