### ISSUE TITLE
カラム幅を保存して欲しいです。

### ISSUE THREAD

**Issue by mintia666** [noriokun4649/TVTComment#83]
いつも（ほぼ毎日）利用させてもらってます。更新ありがとうございます！
要望になりますが「ログ」タブと、コメント入力欄のカラム幅を保存して欲しいのですが、難しいでしょうか？出来ればで結構ですのでよろしく願いします！
![名称未設定 3](https://user-images.githubusercontent.com/79851969/208227200-f6706bdf-88c1-43b6-a4b8-979466f3a3e3.jpg)

**Comment by noriokun4649** [comment]
ログ欄のカラムに関しては既に保存されるようになっています。当方の環境で保存されることも確認しております。
TvTestを終了するのではなく、TvTCommentの設定ウィンドウ側を×で終了して、カラムの幅が保存されるか確認していただけますか？
もし、この方法で正常にカラム幅が保存されるのであれば、TvTest側でプラグインの終了処理が正常に行われていない可能性があります。

コメント入力欄のスプリッター幅については、保存に対応させてみようと思います。

**Comment by mintia666** [comment]
ログ欄のカラムはちゃんと保存されておりました！失礼いたしました！
コメント入力欄の方の対応ありがとうございます！
